export * from './ping.controller';
export * from './persona-documento.controller';
export * from './persona-estado.controller';
export * from './estado-persona.controller';
export * from './usuario.controller';
export * from './usuario-tipo-usuario.controller';
export * from './tipo-usuario-usuario.controller';
export * from './cargar-archivo.controller';
export * from './descarga-archivos.controller';
